version: "3.7"
services:
  release:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    # This is set this way to make things easier in the Actions workflows.
    image: image

  run-model:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ./test-job.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw
      - ./log:/data/log:rw

  validate:
    image: 3scale/ajv
    volumes:
      - ./output-schema.json:/data/schema.json
      - ./output:/data/output
    command: validate -s schema.json -d output/data.json
